apiVersion: v1
kind: Service
metadata:
  name: grpc-retry-fun
  namespace: new
  labels:
    app.kubernetes.io/name: grpc-retry-fun
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grpc-retry-fun
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
